create database simple_database;
CREATE TABLE person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (100) NOT NULL,
    age int check (age>0) NOT NULL,
    email varchar(100) NOT NULL,
    address varchar (200) NOT NULL
);

ALTER TABLE person ADD COLUMN date_of_birth DATE;

ALTER TABLE person ADD COLUMN created_at TIMESTAMP;

ALTER TABLE person ADD COLUMN mood int;